#!/bin/bash
# Copyright 2013 Numenta Inc.
#
# Copyright may exist in Contributors' modifications
# and/or contributions to the work.
#
# Use of this source code is governed by the MIT
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

# Checks for modified .template files and warns user if any were modified

MODIFIED=`git diff --name-only HEAD@{1} | grep -E '\.(hpp|cpp|i|conf)$'`
if [ ! "$MODIFIED" = "" ]; then
    echo ""
    echo "WARNING: The following modified files require a build."
    echo -e "$MODIFIED"
    echo ""
fi
