# Linked clones requires version 1.8
Vagrant.require_version ">= 1.8"

# Calculate project root dir
PROJECT_ROOT = File.expand_path("../../..", File.dirname(__FILE__))

Vagrant.configure(2) do |config|
  config.vm.box = "AndrewDryga/vagrant-box-osx"
  config.vm.provider "virtualbox" do |vb|
    # Use linked clones instead of importing hard-disk
    vb.linked_clone = true
  end

  # Additional provisioning for requirements not satisfied by image alone.
  # Arguments:
  #   1) node version
  config.vm.provision "shell", path: "vagrant-provision.sh", args: []

  # Use pseudoterminal.  Required for use in bamboo.
  config.ssh.pty = true

  # Share project root directory
  config.vm.synced_folder PROJECT_ROOT, "/shared", type: "rsync",
    owner: "vagrant", group: "staff",
    rsync__exclude: ".git/"
end
